ezsystems/ezplatform-ee-demo

- app/config/ezplatform.yml
> studio_template from eZStudioDemoBundle

- app/Resources/EzSystemsRecommendationBundle/views/recommendations.html.twig
- composer.json
Added recommendations bundle dependencies.
Created template for displaying recommendations in app folder (proper way by EzSystemsRecommendationsBundle)
JIRA: https://jira.ez.no/browse/EZS-695
> EZS-695 [Studio Demo] - Include trending articles

- app/AppKernel.php
- app/config/routing.yml
Added Recommendation Bundle to AppKernel.php and routing.
> No Recommendation Bundle causes assetic error.

- app/config/env.php
> Yoochoose keys in env.php

- app/Resources/EzSystemsRecommendationBundle/views/missing_recommendations.html.twig
- app/Resources/EzSystemsRecommendationBundle/views/recommendations.html.twig
- app/Resources/EzSystemsRecommendationBundle/views/show_recommendations.html.twig
https://jira.ez.no/browse/EZS-867
Preloader screen (old font):
Recommended articles (old font):
--
Updated font for the recommended articles label and cards titles:
> EZS-867: Design improvement for the recommended articles

- app/AppKernel.php
- composer.json
https://jira.ez.no/browse/EZS-979
> EZS-979: Remove search prototype from requirements

- README.md
Reverts ezsystems/ezstudio-demo#10
> Revert "Improved README.md"

- app/Resources/EzSystemsRecommendationBundle/views/missing_recommendations.html.twig
- app/Resources/EzSystemsRecommendationBundle/views/recommendations.html.twig
- app/Resources/EzSystemsRecommendationBundle/views/show_recommendations.html.twig
https://jira.ez.no/browse/EZS-1044
requires https://github.com/ezsystems/ezstudio-demo-bundle/pull/115 before merge
> EZS-1044: The personalization block is missing one of the recommended articles

- app/config/ezplatform.yml
https://jira.ez.no/browse/DEMO-2
Additional fields group configuration introduced in https://github.com/ezsystems/ezstudio-demo-bundle/pull/120
> DEMO-2: As a marketer, I want to be able to customize the meta

- app/config/ezplatform.yml
https://jira.ez.no/browse/DEMO-32
> DEMO-32: Update the FieldGroup of all the Content Types (add missing meta configuration)

- app/Resources/EzSystemsFormBuilderBundle/views/fields/email/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/field.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/paragraph_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/single_line_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/submit_button.html.twig
JIRA: https://jira.ez.no/browse/EZS-1225
ping @lserwatka
> EZS-1225 Add form builder fields templates to Studio-demo

- app/Resources/EzSystemsPersonalizedBlockBundle/views/horizontal.html.twig
- app/Resources/EzSystemsPersonalizedBlockBundle/views/personalized.html.twig
- app/Resources/EzSystemsPersonalizedBlockBundle/views/vertical.html.twig
https://jira.ez.no/browse/DEMO-67
> DEMO-67: Update design of Personalization block

- app/AppKernel.php
**JIRA ticket related**: https://jira.ez.no/browse/EZS-1255
> EZS-1255: CronBundle is missing in AppKernel

- app/Resources/EzSystemsFormBuilderBundle/views/fields/captcha/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/date/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/file/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/url/basic.html.twig
JIRA: https://jira.ez.no/browse/EZS-1354
> EZS-1354 Some form fields templates are missing.

- app/Resources/EzSystemsFormBuilderBundle/views/fields/date/basic.html.twig
https://jira.ez.no/browse/EZS-1352
Date form field has no Required field
> EZS-1352 Date form field has no Required field

- app/Resources/EzSystemsFormBuilderBundle/views/fields/dropdown/basic.html.twig
https://jira.ez.no/browse/EZS-1369
> EZS-1369 Dropdown field width is not aligned with other fields

- app/Resources/EzSystemsFormBuilderBundle/views/fields/checkbox/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/radio/basic.html.twig
https://jira.ez.no/browse/EZS-1370
> EZS-1370 Radio & Checkbox fields - missing extra space

- README.md
> Change Studio to Enterprise in readme

- app/AppKernel.php
- app/Resources/NetgenTagsBundle/views/admin/header.html.twig
- app/Resources/NetgenTagsBundle/views/tag/view.html.twig
- app/config/routing.yml
- composer.json
https://jira.ez.no/browse/DEMO-91
required by https://github.com/ezsystems/ezstudio-demo-bundle/pull/173
> DEMO-91: Add TagBundle to eZ Studio Demo

- app/Resources/EzSystemsFormBuilderBundle/views/fields/captcha/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/checkbox/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/date/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/dropdown/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/email/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/file/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/paragraph_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/radio/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/single_line_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/url/basic.html.twig
https://jira.ez.no/browse/DEMO-92
> DEMO-92: Render the Form UI as per the designs for 1/2/3 column

- behat.yml.dist
Jira: https://jira.ez.no/browse/EZEE-1516
Adding of one line to imports for ezstudio demo bundle.
Required by ezsystems/ezstudio-demo-bundle#186.
> [Behat] EZEE-1516: Add behat suites line for ezstudio demo bundle

- app/AppKernel.php
- app/config/routing.yml
- composer.json
https://jira.ez.no/browse/DEMO-102
related issue: https://github.com/ezsystems/ezstudio-demo-bundle/pull/185
> DEMO-102: Nova SEO bundle in Studio Demo Site

- app/Resources/EzSystemsRecommendationBundle/views/recommendations.html.twig
- app/Resources/EzSystemsRecommendationBundle/views/show_recommendations.html.twig
JIRA: https://jira.ez.no/browse/EZEE-1382
> EZEE-1382 Add custom filters to a request to eZ Recommendation

- src/AppBundle/MigrationVersions/users.yml
> JIRA: https://jira.ez.no/browse/EZEE-1841
This PR changes Anonymous permissions so that this role is allowed to read and view embedded  content in Media. This is needed in order to provide accurate preview in Landing Page editor.
> EZEE-1841: Cannot generate preview for Content outside the Home tree in Studio blocks

- app/config/routing.yml
- src/AppBundle/Resources/public/js/views/up-itemsfieldview.js
https://jira.ez.no/browse/DEMO-144
> DEMO-144: [User Profiling block] unable to fetch autocomplete for tags

- app/config/default_parameters.yml
https://jira.ez.no/browse/DEMO-145
> DEMO-145: Cannot use File form field in Form Block

- src/AppBundle/MigrationVersions/all.yml
- src/AppBundle/MigrationVersions/users.yml
https://jira.ez.no/browse/DEMO-146
> DEMO-146: Error rendering block for Embed and Gallery preview

- .ez.yml
- INSTALL.md
- README.md
- app/Resources/EzSystemsFormBuilderBundle/views/fields/captcha/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/checkbox/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/date/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/dropdown/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/email/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/field.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/file/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/paragraph_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/radio/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/single_line_text/basic.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/submit_button.html.twig
- app/Resources/EzSystemsFormBuilderBundle/views/fields/url/basic.html.twig
- app/Resources/NetgenTagsBundle/views/admin/header.html.twig
- app/config/default_parameters.yml
- app/config/ezplatform.yml
- behat.yml.dist
- behat_suites.yml
- composer.json
Trying to merge 1.13 into 2.0, this will most likely allow us to merge 2.0 into master as well and fixup master.
Please check for changes that should *not* be in 2.0.
review ping @damianz5 @mnocon
> Studio demo 1.13 merge to 2.0

- app/config/default_parameters.yml
- app/config/services/app.yml
- src/AppBundle/AppBundle.php
- src/AppBundle/DependencyInjection/Compiler/MigrationParameterPass.php
- src/AppBundle/MigrationVersions/users.yml
- src/AppBundle/Resources/public/js/views/up-itemsfieldview.js
https://jira.ez.no/browse/EZEE-1900
> EZEE-1900: Installer fails if auto_increment_increment != 1

- app/AppKernel.php
- app/Resources/views/page_head.html.twig
- app/config/nova_ezseo.yml
- app/config/routing.yml
- composer.json
- src/AppBundle/MigrationVersions/all.yml
- src/AppBundle/MigrationVersions/product_list.yml
> nova seo bundle

- app/config/ezplatform.yml
https://jira.ez.no/browse/EZP-29047
> EZP-29047: Youtube custom tag not rending on the front-end

- composer.json
DEMO-161: Preview fails for what appears to be a non published object / draft
https://jira.ez.no/browse/DEMO-161
> DEMO-161: Preview fails for non published draft

- INSTALL.md
Nitpick fixes in installation instructions for ezplatform-ee-demo.
> Fix for repository url and folder nitpicks

- app/Resources/views/blocks/_block.html.twig
- app/Resources/views/blocks/userprofiling.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/banner.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/banner_container.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/collection.content.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/contentlist.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/embed.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/gallery.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/keyword.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/maform.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/map.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/places.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/rss.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/tag.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/video.html.twig
- app/config/default_layouts.yml
- src/AppBundle/MigrationVersions/schema-ee_mysql.sql
**JIRA**: http://jira.ez.no/browse/EZEE-2040
This is not stand-alone Pull Request
===
Its required for:
- https://github.com/ezsystems/ezplatform-page-fieldtype/pull/8
- https://github.com/ezsystems/ezplatform-page-builder/pull/47
> EZEE-2040: Design tab of Block configuration

- src/AppBundle/MigrationVersions/landing_page_contenttype.yml
https://jira.ez.no/browse/DEMO-166
> DEMO-166: Move 'Landing page' to a separate content type group

- app/config/ezplatform.yml
Reverts ezsystems/ezplatform-ee-demo#61
Turns out configuration was already there: https://github.com/ezsystems/ezplatform-ee-demo/blob/master/app/config/views.yml#L4
> Revert "DEMO-169: Pagelayout is not defined in configuration"

- app/Resources/views/themes/tastefulplanet/zone/zone.html.twig
> JIRA: https://jira.ez.no/browse/EZEE-1951
> Requires: https://github.com/ezsystems/ezplatform-page-fieldtype/pull/19 https://github.com/ezsystems/ezplatform-page-builder/pull/81
> EZEE-1951: Unable to save new Page

- app/Resources/views/blocks/_block.html.twig
- src/AppBundle/MigrationVersions/schema-ee_mysql.sql
JIRA: https://jira.ez.no/browse/EZEE-2090
> EZEE-2090: Implemented tabs mechanism for Block Configuration

- app/Resources/views/themes/tastefulplanet/full/product_list.html.twig
- app/config/image_variations.yml
- web/assets/css/article.css
- web/assets/css/blog.css
- web/assets/css/footer.css
- web/assets/css/product_list.css
- web/assets/css/subscribe.css
jira issue: https://jira.ez.no/browse/DEMO-173
**added spacing between title and list**
**optimized banner and spacing between blog posts on mobile**
**optimized search and banner for mobile**
**reworked search and filters**
**changed image variation to keep aspect ratio of images**
We don't mess with the tomato soup ;)
> DEMO-173: design improvements

- app/Resources/views/themes/tastefulplanet/layouts/1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1_2.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1_2__1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/2_1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/2_1__1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/container.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/home.html.twig
- app/Resources/views/themes/tastefulplanet/zone/zone.html.twig
https://jira.ez.no/browse/EZEE-2122
> EZEE-2122: Remove Studio related element identifiers

- src/AppBundle/MigrationVersions/schema-ee_mysql.sql
JIRA: https://jira.ez.no/browse/EZEE-2110
Depends on: https://github.com/ezsystems/ezplatform-page-builder/pull/84
> EZEE-2110: Change data format from DATETIME to INT (timestamp)

- app/Resources/views/themes/tastefulplanet/zone/zone.html.twig
> JIRA: https://jira.ez.no/browse/EZEE-2053
> Requires: https://github.com/ezsystems/ezplatform-page-builder/pull/121 https://github.com/ezsystems/ezplatform-page-fieldtype/pull/28
> EZEE-2053: HTTP cache for Page Builder

- web/assets/scss/_base.scss
jira issue: https://jira.ez.no/browse/DEMO-175
> DEMO-175: Add style for blockquote

- tests/AppBundle/Behat/EnterpriseDemoEnvironmentConstants.php
Update EnterpriseDemoEnvironmentConstants class.
JIRA: https://jira.ez.no/browse/EZP-29143
> EZP-29143 run test features on Demo version without changing feature files

- app/config/views.yml
- src/AppBundle/QueryType/ChildrenQueryType.php
Reverts ezsystems/ezplatform-ee-demo#78
additional works is needed here, also templates are missing
> Revert "DEMO-194: User is unable to embed Products in LP"

- app/Resources/views/themes/tastefulplanet/block_item/product_list.html.twig
- app/Resources/views/themes/tastefulplanet/block_item_wide/product.html.twig
- app/Resources/views/themes/tastefulplanet/block_item_wide/product_list.html.twig
- app/config/views.yml
- src/AppBundle/QueryType/ChildrenQueryType.php
https://jira.ez.no/browse/DEMO-194
> DEMO-194: User is unable to embed Products in LP

- app/Resources/views/themes/tastefulplanet/blocks/map.html.twig
https://jira.ez.no/browse/DEMO-206
> DEMO-206: Only one map marker for Places block in edit mode

- app/config/blocks.yml
- app/config/default_layouts.yml
https://jira.ez.no/browse/DEMO-207
> DEMO-207: Template config cleanup

- src/AppBundle/MigrationVersions/form.yml
https://jira.ez.no/browse/DEMO-213
> DEMO-213: Form content type update

- app/Resources/views/themes/tastefulplanet/block_item/card/default.html.twig
- app/Resources/views/themes/tastefulplanet/block_item/list/default.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/schedule/cards.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/schedule/list.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1w__2_1__2_1__1w.html.twig
- app/Resources/views/themes/tastefulplanet/parts/render_description.html.twig
- app/config/default_layouts.yml
- app/config/image_variations.yml
- app/config/services.yml
- app/config/views.yml
- src/AppBundle/Event/TemplateAttributeBlockNameListener.php
- src/AppBundle/Twig/ContentDescriptionExtension.php
- web/assets/scss/blocks/_card.view.scss
- web/assets/scss/demo.scss
bootstrap col-12:
bootstrap col-8:
bootstrap col-6:
bootstrap col-4:
https://jira.ez.no/browse/DEMO-197
> DEMO-197: Content scheduler block on TastefulPlanet

- app/config/services/migration.yml
- src/AppBundle/MigrationVersions/form.yml
https://jira.ez.no/browse/DEMO-216
> DEMO-216: form builder - content item

- web/assets/scss/_blog.post.scss
- web/assets/scss/blocks/_hero.scss
- web/assets/scss/demo.scss
https://jira.ez.no/browse/DEMO-203
> DEMO-203: Hero block title should be responsive

- app/Resources/views/themes/tastefulplanet/parts/render_description.html.twig
jira issue: https://jira.ez.no/browse/DEMO-222
> DEMO-222: Fix issues with special character in block templates

- web/assets/scss/blocks/_gallery.scss
1) Zone wide
2) zone col-12
3) zone col-6 / col-6
4) zone col-8 / col-4
https://jira.ez.no/browse/DEMO-226
> DEMO-226: Set autoscaling for Gallery images

- app/Resources/EzPlatformPageFieldTypeBundle/views/blocks/schedule.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1_2.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/container.html.twig
https://jira.ez.no/browse/DEMO-227
> DEMO-227: Schedule block templates and block default view

- app/config/default_layouts.yml
https://jira.ez.no/browse/DEMO-229
> DEMO-229: Clean up collection templates config

- app/config/image_variations.yml
- web/assets/scss/blocks/_card.view.scss
https://jira.ez.no/browse/DEMO-221
> DEMO-221: Cropping images

- web/assets/scss/blocks/_card.view.scss
https://jira.ez.no/browse/DEMO-232
> DEMO-232: Add gap between columns

- app/Resources/views/themes/tastefulplanet/block_item/blog_post/default.html.twig
- web/assets/scss/_landing.page.scss
jira: https://jira.ez.no/browse/DEMO-238
> DEMO-238: make embedded blog post more consistent

- app/Resources/views/themes/tastefulplanet/fields/ezform_field.html.twig
- app/Resources/views/themes/tastefulplanet/form_builder/default_form_view.html.twig
- app/Resources/views/themes/tastefulplanet/full/form.html.twig
- web/assets/scss/_form.scss
https://jira.ez.no/browse/DEMO-231
> DEMO-231: Embed form improvements

- app/Resources/views/themes/tastefulplanet/full/folder.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1_2.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1_2__1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1w__1__1w.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/1w__2_1__2_1__1w.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/2_1.html.twig
- app/Resources/views/themes/tastefulplanet/layouts/2_1__1.html.twig
- app/Resources/views/themes/tastefulplanet/pagelayout.html.twig
- app/Resources/views/themes/tastefulplanet/zone/zone.html.twig
- app/config/blocks.yml
- app/config/views.yml
- src/AppBundle/MigrationVersions/content.yml
- src/AppBundle/MigrationVersions/product_list.yml
- web/assets/js/main.js
- web/assets/scss/_landing.page.scss
- web/assets/scss/blocks/_card.view.scss
- web/assets/scss/blocks/_contentlist.scss
https://jira.ez.no/browse/DEMO-234
> DEMO-234: followup LP changes

- web/assets/scss/_article.scss
- web/assets/scss/_landing.page.scss
jira: https://jira.ez.no/browse/DEMO-239
> DEMO-239: Improve homepage design (mobile)

- app/Resources/views/themes/tastefulplanet/full/landing_page.html.twig
- composer.json
- web/assets/scss/_personalized.scss
https://jira.ez.no/browse/DEMO-204
> DEMO-204: Personalized block update

- app/config/default_layouts.yml
Reorder and rename Design tab items for Content list and Collection blocks
https://jira.ez.no/browse/DEMO-247
> DEMO-247: Reorder and rename Design tab items

- app/Resources/views/themes/tastefulplanet/layouts/1w__2_1__2_1__1w.html.twig
https://jira.ez.no/browse/DEMO-253
> DEMO-253: Cards and List layout don't render good on 6 zones template

- app/Resources/views/themes/tastefulplanet/full/folder.html.twig
https://jira.ez.no/browse/DEMO-250
> DEMO-250: Display Folder title even when Image is not added

- app/config/services.yml
- src/AppBundle/Menu/ReorderMenuListener.php
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29171
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Adds priority to series of menu listeners to build it in correct order.
https://github.com/ezsystems/ezplatform-form-builder/pull/105
https://github.com/ezsystems/ezplatform-admin-ui/pull/700
https://github.com/ezsystems/ezplatform-page-builder/pull/251
> EZP-29171: Update Navbar menu items order

- src/AppBundle/MigrationVersions/all.yml
jira issue: https://jira.ez.no/browse/DEMO-263
> DEMO-263: Change field order for folder

- src/AppBundle/MigrationVersions/schema-ee_mysql.sql
> JIRA: https://jira.ez.no/browse/EZP-29936
> EZP-29936: Synchronize workflow database schema in installers

- web/assets/scss/_landing.page.scss
https://jira.ez.no/browse/DEMO-248
> DEMO-248: Implement CSS cropping style for gallery

- app/config/ezplatform.yml
- app/config/workflows.yml
> JIRA: https://jira.ez.no/browse/EZEE-2647
> JIRA: https://jira.ez.no/browse/DEMO-266
> EZEE-2647: Move existing workflows to demo installation

- app/Resources/translations/custom_tags.en.yaml
- app/Resources/views/themes/tastefulplanet/fields/ezrichtext/custom_tags/call_to_action.html.twig
- app/Resources/views/themes/tastefulplanet/fields/ezrichtext/custom_tags/factbox.html.twig
- app/config/fields/ezrichtext/custom_tags.yml
- web/assets/scss/_custom.tags.scss
- web/assets/scss/demo.scss
jira issue: https://jira.ez.no/browse/DEMO-274
> DEMO-274: New custom tags

- app/config/blocks.yml
https://jira.ez.no/browse/DEMO-270
> DEMO-270: Reorder block icons

- app/AppKernel.php
- app/config/default_layouts.yml
- src/AppBundle/MigrationVersions/all.yml
- src/AppBundle/MigrationVersions/users.yml
https://jira.ez.no/browse/DEMO-279
> DEMO-279: fixes for 2.4.1 release

- web/assets/scss/blocks/_contentlist.scss
https://jira.ez.no/browse/DEMO-290
> DEMO-290: Fix for ezimage field height on places content list

- src/AppBundle/Event/Subscriber/EndWorkflowSubscriber.php
- src/AppBundle/Event/Workflow/PublishOnLastStageSubscriber.php
- src/AppBundle/MigrationVersions/users.yml
Move the workflow to the last stage when content item is published
https://jira.ez.no/browse/DEMO-285
> DEMO-285: Move the workflow to the last stage when content item is pub

- src/AppBundle/MigrationVersions/users.yml
https://jira.ez.no/browse/DEMO-283
> DEMO-283: As an `Editor` I should be able use workflow

- app/Resources/views/themes/tastefulplanet/blocks/places/cards.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/tastes/cards.html.twig
- app/Resources/views/themes/tastefulplanet/blocks/tastes/home.html.twig
https://jira.ez.no/browse/DEMO-297
> DEMO-297: Preview does not render for Places and Tastes blocks

- app/Resources/views/themes/tastefulplanet/block_item/place/wide.html.twig
https://jira.ez.no/browse/DEMO-304
> DEMO-304: The "Wide" view of a "Place" content breaks HTML

- app/Resources/views/themes/tastefulplanet/blocks/places/map.html.twig
https://jira.ez.no/browse/DEMO-300
> DEMO-300: `Map` design doesn't work for `Places` block

- tests/AppBundle/Behat/PageElement/BlockPreview/DemoBannerPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/DemoContentListPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/DemoEmbedPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/DemoGalleryPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/DemoRSSPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/DemoVideoPreview.php
- tests/AppBundle/Behat/PageElement/BlockPreview/HeroPreview.php
- tests/AppBundle/Behat/PageElement/DemoEnterpriseElementFactory.php
- tests/AppBundle/Behat/PageObject/DemoEnterprisePageObjectFactory.php
- tests/AppBundle/Behat/PageObject/DemoLandingPagePreview.php
Description in ezsystems/BehatBundle#87
> EZP-30668: move core tests classes from AdminUI to BehatBundle

- app/config/default_parameters.yml
- app/config/services.yml
- src/AppBundle/Event/Subscriber/Recommendation/UserCollectionSubscriber.php
https://jira.ez.no/browse/EZEE-2849
> EZEE-2849: Subsciber example for Recommendation User Collection

- ez.webpack.config.js
- package.json
- web/assets/js/hotjar.js
- webpack.config.js
Using an environment variable will make it simple to configure a new instance (eZ Platform Cloud / platform.sh) with a hotjar tracker.
https://jira.ez.no/browse/DEMO-308
> DEMO-308: As an administrator, I want to configure hotjar with env variables

- src/AppBundle/MigrationVersions/users.yml
https://jira.ez.no/browse/DEMO-310
> DEMO-310: Adding draft removing permissions to Redactor role

- .gitignore
- composer.json
- config/packages/ezplatform.yaml
Add ezrecommendation-client and personalized-block
> DEMO-326: Update the recommendation bundle for v3

- composer.json
- config/packages/ezplatform.yaml
- src/Installer/InstallerCommandExecuteTrait.php
> Changes for symfony5

- templates/themes/maison/card/inspiration.html.twig
- templates/themes/maison/card/store.html.twig
- templates/themes/maison/fields/content_fields.html.twig
- templates/themes/maison/layout/header.html.twig
- templates/themes/professionals/card/professional.html.twig
- templates/themes/professionals/card/professional_catalog.html.twig
- templates/themes/professionals/layout/header.html.twig
Use helper ez_path instead of path to generate url based on given Location object
> Use helper ez_path instead of path

- assets/js/maison/script.js
- assets/scss/_default.scss
- assets/scss/_footer.scss
- assets/scss/maison/_footer.scss
- assets/scss/maison/_forms.scss
- assets/scss/maison/_page.scss
- assets/scss/maison/maison.scss
- config/packages/ezplatform.yaml
- config/routes.yaml
- config/routes/ezplatform_admin_ui.yaml
- config/services/controllers.yaml
- config/services/query_types.yaml
- config/services/search.yaml
- src/Controller/SearchController.php
- src/Form/Data/SearchData.php
- src/Form/Type/SearchType.php
- src/QueryType/SearchQueryType.php
- src/Search/PagerSearchContentMapper.php
- templates/themes/maison/layout/header.html.twig
- templates/themes/maison/search/form.html.twig
- templates/themes/maison/search/index.html.twig
- translations/maison.en.xlf
- translations/messages.en.xlf
- webpack.config.js
https://jira.ez.no/browse/DEMO-335
> DEMO-335: Implemented search results page

- bin/tmp_cache_warmer.php
- config/packages/ezplatform.yaml
- config/packages/views.yaml
- config/services/events.yaml
- src/Event/Listener/RootDomainToSubdomainRedirectListener.php
- src/QueryType/ChildrenQueryType.php
Root domain redirection, professionals duplication fix
> Root domain redirection

- assets/scss/maison/_navigation.scss
- src/Menu/MenuBuilder.php
- templates/themes/maison/layout/header.html.twig
https://jira.ez.no/browse/DEMO-342
> DEMO-342: Commented out broken links

- assets/scss/maison/_navigation.scss
- config/packages/field_templates.yml
- src/Menu/MenuBuilder.php
- templates/themes/maison/full/store.html.twig
- templates/themes/maison/layout/header.html.twig
- translations/maison.en.xlf
- translations/menu.en.xlf
https://jira.ez.no/browse/DEMO-343
> DEMO-343: Linked Customer Service to Connect with us

- config/packages/ezplatform.yaml
- src/MigrationVersions/content.yaml
- src/MigrationVersions/content_type.yaml
- src/MigrationVersions/professionals.yaml
- templates/themes/maison/block_item/inspiration/wide.html.twig
- templates/themes/maison/blocks/content_list/icons.html.twig
- templates/themes/maison/blocks/content_list/tiles.html.twig
- templates/themes/maison/card/inspiration.html.twig
- templates/themes/maison/full/inspiration.html.twig
- templates/themes/maison/menu/inspirations_menu.html.twig
- templates/themes/maison/search/index.html.twig
- templates/themes/professionals/card/professional.html.twig
- templates/themes/professionals/full/professional.html.twig
https://jira.ez.no/browse/DEMO-352
> DEMO-352: Restructured content under Inspiration

- src/MigrationVersions/content_type.yaml
https://jira.ez.no/browse/DEMO-346
> DEMO-346: Restructured content under Furniture

- src/MigrationVersions/content_type.yaml
https://jira.ez.no/browse/DEMO-351
> DEMO-351: Restructured content under Room

- templates/themes/maison/search/index.html.twig
> JIRA: -
Added check if video field is defined in search result
> Added check if video field is defined in search result

- src/MigrationVersions/content_type.yaml
https://jira.ez.no/browse/DEMO-376
> DEMO-376: Content Structuring under B2B Program sub-tree

- src/MigrationVersions/content_type.yaml
https://jira.ez.no/browse/DEMO-375
> DEMO-375: Content structuring under Customer Service (FAQ, Contact Us, Find Reseller)

- src/MigrationVersions/content_type.yaml
https://jira.ez.no/browse/DEMO-374
> DEMO-374: Content Structure for About page

- src/MigrationVersions/content.yaml
- src/MigrationVersions/content_type.yaml
- templates/themes/maison/card/blog_post.html.twig
- templates/themes/maison/full/blog_post.html.twig
https://jira.ez.no/browse/DEMO-377
> DEMO-377: Content Restructuring under Blog (Blog & Blog Post)

- src/MigrationVersions/all.yaml
- src/MigrationVersions/content_type.yaml
- src/MigrationVersions/folder.yaml
- src/MigrationVersions/professionals_directory.yaml
- templates/themes/professionals/card/professional_catalog.html.twig
- templates/themes/professionals/full/folder.html.twig
https://jira.ez.no/browse/DEMO-400
> DEMO-400: Update to Furniture and B2B sub-tree
